// Code generated by "stringer -type=ArgType"; DO NOT EDIT.

package flax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ArgTypeShort-0]
	_ = x[ArgTypeLong-1]
	_ = x[ArgTypeDoubleDash-2]
	_ = x[ArgTypeProgram-3]
	_ = x[ArgTypeInvalid-4]
}

const _ArgType_name = "ArgTypeShortArgTypeLongArgTypeDoubleDashArgTypeProgramArgTypeInvalid"

var _ArgType_index = [...]uint8{0, 12, 23, 40, 54, 68}

func (i ArgType) String() string {
	if i >= ArgType(len(_ArgType_index)-1) {
		return "ArgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArgType_name[_ArgType_index[i]:_ArgType_index[i+1]]
}
